export const DANG_NHAP_ACTION = "DANG_NHAP_ACTION";
export const DANG_KY_ACTION = "DANG_KY_ACTION";
export const SET_THONG_TIN_NGUOI_DUNG = "SET_THONG_TIN_NGUOI_DUNG";

export const GET_USER_LIST = "GET_USER_LIST";

export const EDIT_USER = "EDIT_USER";
export const GET_USER_INFO = "GET_USER_INFO";
